[project]
name = "vicare-exporter"
# dummy version
version = "0.0.0"
description = "Prometheus exporter for ViCare metrics"
authors = [{name="Sebastian Eckweiler", email="seb.eckweiler@gmail.com"}]
requires-python = ">=3.10"
dependencies = [
    "prometheus-client>=0.25.0",
    "python-dotenv>=1.2.2",
    "pyvicare>=2.60.2",
    "requests>=2.34.2",
]

[project.scripts]
vicare-exporter = "vicare_exporter.__main__:main"

[tool.uv]
package = true

[tool.isort]
profile = "black"
line_length = 1000

[tool.flake8]
max-line-length = 1000
ignore = "E203"

[tool.pytest.ini_options]
addopts = "--junit-xml=test-results.xml"
testpaths = ["tests"]

[dependency-groups]
dev = [
    "black>=26.5.1",
    "pre-commit~=2.20.0",
    "pytest~=8.1.1",
]
