# grep'd from: https://documentation.viessmann.com/static/iot/data-points

HEATING_CIRCUIT_OPERATING_PROGRAMS = [
    "active",
    "comfort",
    "comfortCooling",
    "comfortCoolingEnergySaving",
    "comfortEnergySaving",
    "comfortHeating",
    "dhwPrecedence",
    "eco",
    "external",
    "fixed",
    "forcedLastFromSchedule",
    "frostprotection",
    "holiday",
    "holidayAtHome",
    "manual",
    "normal",
    "normalCooling",
    "normalCoolingEnergySaving",
    "normalEnergySaving",
    "normalHeating",
    "reduced",
    "reducedCooling",
    "reducedCoolingEnergySaving",
    "reducedEnergySaving",
    "reducedHeating",
    "standby",
    "summerEco",
]

HEATING_CIRCUIT_OPERATING_MODES = [
    "active",
    "cooling",
    "dhw",
    "dhwAndHeating",
    "dhwAndHeatingCooling",
    "forcedNormal",
    "forcedReduced",
    "heating",
    "heatingCooling",
    "normalStandby",
    "standby",
]
