name: Build

on:
  push:
    branches: [ main ]
    tags: [ v* ]

  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: vicare-exporter
  IMAGE_TAGS: latest v1 ${{ github.sha }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v4.1.0
      with:
        platforms: arm64,amd64

    - id: build
      name: Build container image
      uses: redhat-actions/buildah-build@v2.13
      with:
        containerfiles: |
          ./Dockerfile
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.IMAGE_TAGS }}
        platforms: linux/amd64, linux/arm64

    - id: push
      name: Push container image
      uses: redhat-actions/push-to-registry@v2.8
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.IMAGE_TAGS }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}

    - name: Echo outputs
      run: |
        echo "${{ toJSON(steps.push.outputs) }}"
